apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888\

---
apiVersion: v1
kind: Endpoints
metadata:
  name: wil-playground
  namespace: dev
subsets:
  - addresses:
      - ip: 10.42.0.16
    ports:
      - port: 8888
        protocol: TCP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: wil-playground
  namespace: dev
  labels:
    kubernetes.io/service-name: wil-playground
addressType: IPv4
ports:
  - name: ""
    protocol: TCP
    port: 8888
endpoints:
  - addresses:
      - 10.42.0.16
    conditions:
      ready: true